name: magiceye_example
description: Demonstrates how to use the magiceye plugin.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  magiceye:
    path: ../

flutter:
  uses-material-design: true
